<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.validator' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Validator/ValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Symfony/Validator/Validator.php';

return $this->services['api_platform.validator'] = new \ApiPlatform\Core\Bridge\Symfony\Validator\Validator(${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, $this);
