<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.listener.view.validate' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Validator/EventListener/ValidateListener.php';

return $this->services['api_platform.listener.view.validate'] = new \ApiPlatform\Core\Validator\EventListener\ValidateListener(${($_ = isset($this->services['api_platform.validator']) ? $this->services['api_platform.validator'] : $this->load('getApiPlatform_ValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['api_platform.metadata.resource.metadata_factory']) ? $this->services['api_platform.metadata.resource.metadata_factory'] : $this->getApiPlatform_Metadata_Resource_MetadataFactoryService()) && false ?: '_'});
