<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.vjf2obf' shared service.

return $this->services['service_locator.vjf2obf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('contactRepository' => function () {
    $f = function (\App\Repository\ContactRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\ContactRepository']) ? $this->services['App\Repository\ContactRepository'] : $this->load('getContactRepositoryService.php')) && false ?: '_'});
}));
