# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_lucky_number:
    path: /toto
    controller: App\Controller\AleaController::number



app_create_formation:
    path: /toto/save/formation
    controller: App\Controller\FormationController::sauvegarder
    
app_create_formationType:
    path: /toto/create/formation
    controller: App\Controller\FormationController::create

valid_formation:
    path: /toto/valid/formation
    controller: App\Controller\FormationController::valid
    
edit_formation:
    path: /toto/edit/formation/{id}
    controller: App\Controller\FormationController::edit
    


app_create_experience:
    path: /toto/save/experience
    controller: App\Controller\ExperienceController::sauvegarder
    
app_create_experienceType:
    path: /toto/create/experience
    controller: App\Controller\ExperienceController::create

valid_experience:
    path: /toto/valid/experience
    controller: App\Controller\ExperienceController::valid
    
edit_experience:
    path: /toto/edit/experience/{id}
    controller: App\Controller\ExperienceController::edit
    
delete_experience:
    path: /toto/delete/experience
    controller: App\Controller\ExperienceController::delete
    
    
    
app_create_loisir:
    path: /toto/save/loisir
    controller: App\Controller\LoisirController::sauvegarder

app_create_loisirType:
    path: /toto/create/loisir
    controller: App\Controller\LoisirController::create

valid_loisir:
    path: /toto/valid/loisir
    controller: App\Controller\LoisirController::valid
    
edit_loisir:
    path: /toto/edit/loisir/{id}
    controller: App\Controller\LoisirController::edit

    
#::sauvegarder = nom de la méthode defini dans le controller

#Dans le dossier controlleur, le fichier controlleir doit avoir le même nom
#que celui de sa classe ainsi que dans cette page. ici le nom est aleaControlleur
#Le nom du controlleur il doit se terminer par Controlleur