# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_lucky_number:
    path: /toto/{name}-{nameFamily}
    controller: App\Controller\AleaController::number
    
#Dans le dossier controlleur, le fichier controlleir doit avoir le même nom
#que celui de sa classe ainsi que dans cette page. ici le nom est aleaControlleur
#Le nom du controlleur il doit se terminer par Controlleur