<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.listener.view.write' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/EventListener/WriteListener.php';

return $this->services['api_platform.listener.view.write'] = new \ApiPlatform\Core\EventListener\WriteListener(${($_ = isset($this->services['ApiPlatform\Core\DataPersister\DataPersisterInterface']) ? $this->services['ApiPlatform\Core\DataPersister\DataPersisterInterface'] : $this->load('getDataPersisterInterfaceService.php')) && false ?: '_'});
