<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ApiPlatform\Core\DataPersister\DataPersisterInterface' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataPersister/ChainDataPersister.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Doctrine/Common/DataPersister.php';

return $this->services['ApiPlatform\Core\DataPersister\DataPersisterInterface'] = new \ApiPlatform\Core\DataPersister\ChainDataPersister(array(0 => new \ApiPlatform\Core\Bridge\Doctrine\Common\DataPersister(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'})));
