<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9s2ibsg\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9s2ibsg/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9s2ibsg.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9s2ibsg\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container9s2ibsg\srcDevDebugProjectContainer(array(
    'container.build_hash' => '9s2ibsg',
    'container.build_id' => 'a1324928',
    'container.build_time' => 1552319664,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9s2ibsg');
