<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQclrfkg\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQclrfkg/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQclrfkg.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQclrfkg\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQclrfkg\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Qclrfkg',
    'container.build_id' => '491739d2',
    'container.build_time' => 1551697423,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQclrfkg');
